### ISSUE TITLE
From: / To: fields greyed out when going from pre-configured to Advanced tab

### ISSUE THREAD

**Issue by hsieger** [costales/gufw#10]
Current behaviour:

Select a pre-configured rule, e.g. SSH. Then press right arrow key in the bottom right to go to the advanced tab.

The From: and To: fields in the bottom of the window are greyed out. Only the [paste] button is functional, which normally pastes the current IP. This is useless since the fields remain greyed out and cannot be edited.

Expected behaviour:
The From: To: fields should ALWAYS be editable, and so the Port fields! This is what the Advanced tab is made for.
I would like to use standard rules (like SSH, SAMBA etc.) and edit them, for example to limit SSH access to the local network. This is a very common objective and should have been easy to accomplish.

Unfortunately the behaviour is very inconsistent. If I paste my IP using the paste button, it will come up with that IP whenever I create a new rule.

At the moment, the only way I can configure the IP range is by creating a simple rule, then go to Advanced. Only then are the fields NOT greyed out. If I then declare the local network, e.g. From: 192.168.1.0/24, it will show whenever I create a new predefined rule and go to the Advanced tab.

**Comment by costales** [comment]
Hi,

Could you send me a screenshot about the rule to add with the disabled
fields?

Thanks.

**Comment by costales** [comment]
No reply from user

**Comment by bryango** [comment]
Similar issue observed:
![image](https://user-images.githubusercontent.com/26322692/103148400-21a61400-479a-11eb-9819-5e00592cc745.png)
![image](https://user-images.githubusercontent.com/26322692/103148386-13f08e80-479a-11eb-9e40-83489a1eb117.png)
