### ISSUE TITLE
Gufw doesn't recognise apps like Mozilla Firefox?

### ISSUE THREAD

**Issue by mindfulsource** [costales/gufw#11]
I'm in Linux Mint 19.3. Installed latest gufw 20.04.1 via the [Debian sid .deb package](https://packages.debian.org/sid/all/gufw/download).

I want to either monitor or make a rule for Firefox, but this doesn't work. 'Report' tab never shows anything 'mozilla' or 'firefox', and there's no 'mozilla' or 'firefox' item in the Application list to even find in the drop-down menu to test out manually blocking firefox.

(This is just as a test application to see if `guwf` even works.)

Why is basic detection of apps or processes not working in this GUI?

**Comment by costales** [comment]
That is not the Linux behavior, you have to block/allow rules in the ufw, iptables, kernel.
