### ISSUE TITLE
Gufw in linux mint 20 cinnamon

### ISSUE THREAD

**Issue by Dyskutant** [costales/gufw#12]
good evening
I have linux mint 20 cinnamon and the firewall does not start on my system. I reinstalled gufw and it doesn't work.
when I turn on the firewall in the terminal, I get this error:
`` ValueError: Invalid int () literal base 10: 'WARN:' ''

**Comment by costales** [comment]
Hi, can you run gufw from the terminal? Just run the command: gufw
Best regards

**Comment by Dyskutant** [comment]
I can not

**Comment by Dyskutant** [comment]
> Hi, can you run gufw from the terminal? Just run the command: gufw Best regards

I can not

**Comment by costales** [comment]
? Then I can't help you, I would need the dump of the command for debugging.

**Comment by Dyskutant** [comment]
> ? Then I can't help you, I would need the dump of the command for debugging.

a There is a guide on how to extract these data

**Comment by costales** [comment]
Hi,

I can't reproduce in a fresh install of Mint 20. I think is related to [this another issue](https://github.com/costales/gufw/issues/9)?

Best regards.

**Comment by costales** [comment]
Possible duplicate https://github.com/costales/gufw/issues/9
