### ISSUE TITLE
Gufw closes at shutdown

### ISSUE THREAD

**Issue by ScreenLicker** [costales/gufw#13]
Manjaro KDE Plasma (latest release) w/additional Gufw packages installed, Gufw apparently turns itself off at shutdown & have to log in to turn firewall "on" each restart/power-on. Gufw log says "gufw on" multiple times in a row, with no "disabled" log in between due to this. I enabled Gufw at startup, however it still makes me login using admin pw & is in the "off" position until I turn it back on.

![Screenshot_20200812_014022](https://user-images.githubusercontent.com/48935648/89979254-4e1f2080-dc3d-11ea-857c-67e110800bb0.png)

The first & only time Gufw (or my operating system settings) have failed me. Amazing project, love it otherwise!

Thanks!

**Comment by costales** [comment]
Hi,

Could you try it with ufw?

sudo ufw disable
sudo ufw enable

Reboot

sudo ufw status

Thanks in advance

**Comment by ScreenLicker** [comment]
sudo ufw disable
"Firewall stopped and disabled on system startup"

sudo ufw enable
"Firewall is active and enabled on system startup"

reboot
(computer reboots)

sudo ufw status
"Status: inactive"

Can also confirm that the GUI in "off" position after the reboot

**Comment by costales** [comment]
Hi,

Then it is an issue of ufw, not Gufw.

Please, could you fill a [bug here](https://bugs.launchpad.net/ufw)?

Thanks and a hug.
