### ISSUE TITLE
'/usr/lib/python*/site-packages/gufw/gufw.py' not found Ubuntu 20.04

### ISSUE THREAD

**Issue by kevinkk525** [costales/gufw#21]
```
sudo gufw
[sudo] Passwort für kevin: 
/usr/bin/gufw: Zeile 2: [: =: Einstelliger (unärer) Operator erwartet.
ls: Zugriff auf '/usr/lib/python*/site-packages/gufw/gufw.py' nicht möglich: Datei oder Verzeichnis nicht gefunden
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Verbindung ist gescheitert: Connection refused
```

Basically the same issue as mentioned in the other open issue (which doesn't belong there): https://github.com/costales/gufw/issues/9#issuecomment-704216244

**Comment by costales** [comment]
Hi, distro? Best regards.

**Comment by kevinkk525** [comment]
Ubuntu 20.04, sorry only wrote it in the title

**Comment by costales** [comment]
Thanks. Gufw version?
--
Costales.

**Comment by kevinkk525** [comment]
Gufw version 20.04.1-1 patched with #9 
However, I thought this error was the reason my gufw instance refused to work but in a live-cd it works and now after a reboot I got a different error about an invalid MIT-magic-cookie so I fixed that and gufw does now run, despite that error in the console.

**Comment by costales** [comment]
Please, update it from repo. You should see an upgrade to 20.10.0

**Comment by kevinkk525** [comment]
It's the current version on ubuntu 20.04. Can't upgrade. But it's a warning anyway and doesn't affect the program (as my initial assumption was wrong).

**Comment by costales** [comment]
Try this version please:
http://mirrors.kernel.org/ubuntu/pool/universe/g/gui-ufw/gufw_20.10.0-0ubuntu1_all.deb
It works perfect in 20.04 too.

**Comment by kevinkk525** [comment]
I don't have my original setup anymore but seems to work.
