### ISSUE TITLE
Can't edit existing rules anymore

### ISSUE THREAD

**Issue by older-pack** [costales/gufw#25]
I get this message if I try
"Immutable Rule. You can't edit a rule from ufw"

I was able to edit rules a week or so ago.

I also noticed all the "Name" columns are blank (I think they've been blank a while, maybe since upgrading to 20.04 LTS)
And now any new rules I add are now in blue text. All my old rules are (and always were) in red text.

Any idea whats going on?

Ubuntu 20.04 LTS

**Comment by costales** [comment]
Hi,
Gufw has a log file for knowing if the rule is from ufw or from Gufw. Gufw
can't edit a ufw rule. Probably will be a corrupted file, I never saw this
issue before.
Best regards.

**Comment by older-pack** [comment]
> Probably will be a corrupted file

Hi, thanks for the reply. 
Is there any way for me to check/fix the log file?

**Comment by costales** [comment]
Hi,
No, you can't repair that file :(
Best regards.

**Comment by older-pack** [comment]
Ok. So I guess the remedy is complete removal with something like
`$ sudo apt-get purge --autoremove gufw`
and then reinstall.
Thanks.

**Comment by bryango** [comment]
I find that after toggling the "status" off and on in gufw, the rules become un-editable.
I am using `gufw 20.04.1-4` with Manjaro.

![image](https://user-images.githubusercontent.com/26322692/103148473-df310700-479a-11eb-8080-f35f6000225a.png)
