### ISSUE TITLE
Booting issue

### ISSUE THREAD

**Issue by Intruder-6** [costales/gufw#27]
When i click on the GUFW icon(shield) it gives me the login box and then i put in my password but then nothing happens it doesn't open into the GUFW app nothing opens this is in Kali Linux 20.0
Thank you

**Comment by costales** [comment]
Hi!
Could you try this version?
http://mirrors.kernel.org/ubuntu/pool/universe/g/gui-ufw/gufw_20.10.0-0ubuntu1_all.deb
Thanks in  advance!
