### ISSUE TITLE
Gufw doesn't autostart

### ISSUE THREAD

**Issue by LexxFade** [costales/gufw#30]
I'm using this program on my Arch Linux system and for some reasons it doesn't start on boot; instead I have to manually start the service.

**Comment by costales** [comment]
Hi, Gufw isn't a service. Please, just open a Terminal and run "gufw" and
put here if there is any log.
thanks

**Comment by LexxFade** [comment]
It doesn't show any logs when I run the application through terminal.

**Comment by LexxFade** [comment]
Shouldn't gufw start automatically on system boot though? I mean that's the first thing mentioned in the FAQs

**Comment by costales** [comment]
Hi,

> Shouldn't gufw start automatically on system boot though? I mean that's the first thing mentioned in the FAQs

No, it doesn't mention that. Gufw set changes in ufw and ufw in
iptables and iptables is permanent. Rules are permanent between start
ups ;)

If Gufw doesn't give any dump running from Terminal, then, everything
is OK from its side :)

Best regards.
