### ISSUE TITLE
Package license shown as proprietary in Ubuntu Software

### ISSUE THREAD

**Issue by baermathias** [costales/gufw#31]
![Screenshot from 2021-02-11 22-10-27](https://user-images.githubusercontent.com/45003352/107699269-2412ed80-6cb6-11eb-8c7b-c4957c6d0106.png)

**Comment by costales** [comment]
Hi,
Well, could you submit this bug to Ubuntu Store? I'm not managing that.
Thanks in advance!

**Comment by baermathias** [comment]
Do you have a link? I don't know where to open this issue

**Comment by costales** [comment]
Hi, no sorry. I think it should be in Launchpad, but I don't know where :(
