### ISSUE TITLE
A few extra space

### ISSUE THREAD

**Issue by eshagh79** [costales/gufw#33]
There is some extra space in the line 711 & 2765 file:gufw.pot
"NASCAR Racing 2002/03  8 players"
_____________________^
"ManiaDrive HTTP server "
____________________^

It seems Forgot ";" at the end of line 2110 file:gufw.pot
"Network;Services;|Network;File Transfer"
________________________________^

**Comment by eshagh79** [comment]
If this is not a writing problem please let me know.
Because I changed this in Persian translation.
If not, I will restore it

**Comment by costales** [comment]
Hi, yes, it was a typo. Thanks for the feedback.
--
Costales
