### ISSUE TITLE
Installation problem using Fedora 34 and RPM Sphere

### ISSUE THREAD

**Issue by SpiritSaint** [costales/gufw#38]
This isn't a real problem but this issue will be a great user guide to use `gufw` on Fedora. I haven't use this app in other versions of Fedora. 

## Reproduce

- Make a clean installation of fedora 34 and use RPM Sphere to install gufw. By default gufw isn't available on Fedora 34 repos.
- Run `sudo gufw` and look the errors.

## How to fix them

Well, that's very simple.

I do something like this:

Follow the INSTALL instructions but that doesn't solves the problem.

 The `INSTALL` will replace the `/usr/bin/gufw` and `/usr/bin/gufw-pkexec` files so that's great because just one more step is needed:

Right now you should open `/usr/bin/gufw-pkexec` file and change the file to:

```bash
#!/bin/bash
python3 /usr/lib/python3.9/site-packages/gufw/gufw.py $1
```

The old line have a wrong path. That's all.

**Comment by costales** [comment]
Hi, but that has another path now:
https://github.com/costales/gufw/blob/master/bin/gufw-pkexec#L2
Could you confirm if it's working with that?
Thank you!
