### ISSUE TITLE
Gufw 21.04.0 - Log section Empty?

### ISSUE THREAD

**Issue by 0pLuS0** [costales/gufw#44]
Hello,

I'm running Gufw 21.04.0 with ufw-0.36.1 and rsyslog-8.2110.0 on Slackware 14.2.

When I look at the Log section in Gufw, it only shows me this info;

[01/17/2022 09:29:43 PM] ufw Logging: Medium
[01/17/2022 09:29:35 PM] Gufw Log: Removed

I have /var/log/ufw.log where I see various logging info like;

Jan 17 19:50:57 slack kernel: [UFW AUDIT] IN= OUT=tun0 SRC=10.23.0.33 DST=10.23.0.1 LEN=70 TOS=0x00 PREC=0x00 TTL=64 ID=64565 DF PROTO=UDP SPT=60289 DPT=53 LEN=50
Jan 17 19:50:57 slack kernel: [UFW ALLOW] IN= OUT=tun0 SRC=10.23.0.33 DST=10.23.0.1 LEN=70 TOS=0x00 PREC=0x00 TTL=64 ID=64565 DF PROTO=UDP SPT=60289 DPT=53 LEN=50
Jan 17 19:50:57 slack kernel: [UFW AUDIT] IN= OUT=tun0 SRC=10.23.0.33 DST=10.23.0.1 LEN=74 TOS=0x00 PREC=0x00 TTL=64 ID=64622 DF PROTO=UDP SPT=52840 DPT=53 LEN=54

I thought this type of logging information would also appear in the Gufw log section?

Here is a screen shot of Gufw, showing only those 2 lines I mentioned before.

![gufw](https://user-images.githubusercontent.com/36190223/149892177-6e03e52d-9b8b-4bc0-952e-280c72e81ae3.png)

**Comment by costales** [comment]
Hi,
The Gufw log is only from the Gufw actions ;) then ufw log will not appear
in there.
Best regards

**Comment by 0pLuS0** [comment]
Oh, when making changes in the Preferences, Profiles, Rules, etc...?

Thanks

**Comment by costales** [comment]
Yes ;) or adding rule, etc
Best regards
