### ISSUE TITLE
Is this a Bug?  Profiles Just Merge All Rules -- So, What's the Point of Profiles?

### ISSUE THREAD

**Issue by amiga-500** [costales/gufw#46]
So i was intrigued to try gufw because it includes "Profiles" where i can set rules that i assumed would be kept  independent from other profiles i create.  It's like "Zones" in almost every firewall app.   Great!  ufw has been sorely lacking in that department.  So now i should be able to switch to different sets of rules for different situations e.g. when i take my laptop outside i select "Public" to set the rules i want for publc.  And when home i select "Home" for those other set of rules.  No overlapping.  Makes sense.

HOWEVER, upon testing it seems that is not what is being done.  Huh?   Is this a bug?  It's clear that ALL rules are merged.  So when i select different profiles all their rules are now exactly the same.   I'm scratching my head in wondering how that makes sense.  Version 22 so it's clear this is a feature??

Curious, if this is not a bug then I would love to know why profiles exist at all when at the end of the day rules created for each profile just get combined into one all encompassing ruleset.  Maybe i am supposed to set something to prevent this?

Just now i see in the FAQ saying: "_**I see some rules in all profiles: All the ufw rules will be appear in all profiles**_"

Although i understand that ufw doesnt have any understanding of profiles (outside application.profile) I don't understand why gufw doesnt have it's own config file that keeps track of each user-created profile so when the user switches between them gufw removes the old rules from ufw and puts the new ones in place?  Meaning, why is it necessary to merge all the rules, defeating the purpose of profiles?

Thanks for any clarification.  I am going to assume that there must be some steps i am missing that stops this from happening because I can't possibly believe this is an intended feature.  Maybe its a bug.

I am using Ubuntu 20.04 LTS ... I was using older gufw 20.04.1 via the Ubuntu store but came here to install the latest (22.04).  Problem still exists.

Btw, your "INSTALL" file is out of date..the url doesnt work.  You might want to set the url to this git instead.

Regards

**Comment by costales** [comment]
Hi,
You see combined rules, because of the rules added with ufw ;)
Best regards.
