### ISSUE TITLE
Not able to add individual apps to rules.

### ISSUE THREAD

**Issue by Shaun-OTG-PTHM** [costales/gufw#49]
It seems that we can create our own rules. But when we do not know the ports the app is using it would be handy to have an option where we can select from a menu system or installed apps to add to a rule. Sorry i am not an IT pro so if this is an easy fix on my end i cant seem to find it.

**Comment by costales** [comment]
Hi, you can see the current ports from running apps into the Report tab:

![image](https://github.com/costales/gufw/assets/5886786/235bf65b-57e1-4a20-8b80-f7b9ba12157e)

Best regards.
