### ISSUE TITLE
gufw on debian bullseye "Could not determine the accessibility bus address"

### ISSUE THREAD

**Issue by MoDi86** [costales/gufw#50]
Hi together,

I try to let gufw 20.04 work on debian bullseye. It is the version the apt-Installer got from the debian repository. First, I run to in an issue, where the gufw package was not found. To clean this issue, I point the executable path towards /usr/share/gufw/gufw.py by editing /usr/bin/gufw-pkexec. Then I restarted gufw-pkexec and the message "Could not determine the accessibility bus address" was around in the terminal. Besides, the firewall configuration window opened. At the version 22.04 the same issue appears. How this issue can be cleared?

with best regards,
MoDi86

**Comment by costales** [comment]
Hi,
I think is a systemd issue and not a Gufw issue :(
Best regards.
