### ISSUE TITLE
How to apply multi-profile?

### ISSUE THREAD

**Issue by kincjf** [costales/gufw#52]
hello. I am using gufw on ubuntu 20.
Since the firewall application pattern for each user group is different, [profile A. Profile B, C, ...] was created.

I want to operate two or more Profiles to be activated/deactivated and applied at the same time

The aws security group was really convenient, I made two or more security groups in advance for each condition, and applied more than two security groups to one vm.
=> I want to use gufw like the way aws security group is used, is there a way?

**Comment by costales** [comment]
Hi,
That is not possible, only 1 profile could be enabled.
Best regards.
