### ISSUE TITLE
IP address only?  Why not computer name/device name?

### ISSUE THREAD

**Issue by youngkzy** [costales/gufw#56]
I appreciate the Firewall and ease of use configuration. 

My home network is systems are all DHCP.  I don't want to modify my router to manage static IP addresses.  I was setting up a remote desktop connection through REMMINA and I had to address firewall settings on my Linux Mint Laptop.  Yes, I have the latest version installed and Linux Mint is up-to-date.  I am not usually into firewall settings unless to do something like this.  I found that I need to put in the actual IP address of my Windows PC. I can certainly ping it by its router name. 

For example a windows PC name =
"DESKTOP-ABC123XYZ.fios-router.home"  I can ping it by "DESKTOP-ABC123XYZ" as well. 

You cannot even put in "LOCALHOST" to refer to the self-named.  However you can inject the local IP Address of the Linux machine. 

Error Bad destination address.
Error Bad source address.

Am I missing something?  I tried to find information in the HELP, but it's just a info pop-up.

Please help. 
Thanks.

**Comment by costales** [comment]
Hi, please fill a question for the project ufw in Launchpad. Best regards
