### ISSUE TITLE
Thanks for Gufw! I just released a visual indicator for the gnome status bar which plays nice with it

### ISSUE THREAD

**Issue by illtellyoulater** [costales/gufw#60]
Hi! 

Thank you for building Gufw! I've only discovered a week ago and was really delighted to finally discover such a nice and functional GUI. One feature I was looking for is the ability to show a nice visual indicator for the ufw status, at least for gnome, which I am currently using. 

However I couldn't find anything like that so I decided to build it myself. 

I thought people here would likely be interested in it, so please forgive my shameless plug to it :) 

I've just released v1.0.0 and you can find more about it at https://github.com/illtellyoulater/ufw-status-indicator, where you'll more screenshots and detailed installing instructions.

Thank you again and I hope you guys will enjoy using it as much as I enjoy using Gufw. 

![ufw-status-indicator-ufw-enabled](https://github.com/costales/gufw/assets/3078931/b14340b8-745c-4f89-aef9-2944934941fd)

**Comment by costales** [comment]
Thank you very much @illtellyoulater Good work!! ♥
