### ISSUE TITLE
Missing "DEV_extra_translations" from 24.04 release

### ISSUE THREAD

**Issue by mac-a-r0ni** [costales/gufw#64]
The build fails with the download release archive because it's missing this dir from the repo.

Builds from a git clone, but it's frowned upon to submit a script for my distro (Slackware) that uses any online methods of building besides fetching the available archive.

Would be grateful for a fix!

**Comment by costales** [comment]
Hi, the unique releases are here: https://github.com/costales/gufw/releases
That DEV_extra_translations is into the source, but better, use the releases.
Best regards.
