### ISSUE TITLE
Warning/errors in profiles are not handled

### ISSUE THREAD

**Issue by gileri** [costales/gufw#9]
Hello, thank you for this useful piece of software !

My ufw configuration is invalid :

```
# ufw status
WARN: Duplicate profile 'mosh', using last found
Status: inactive
```

While this warning should be fixed on my side, it shouldn't crash gufw (version 20.04.1):

```
# gufw
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/gufw/gufw.py", line 30, in <module>
    gufw = Gufw(controler.get_frontend())
  File "/usr/lib/python3.8/site-packages/gufw/gufw/view/gufw.py", line 80, in __init__
    self._set_initial_values()
  File "/usr/lib/python3.8/site-packages/gufw/gufw/view/gufw.py", line 283, in _set_initial_values
    self.listening = ListeningReport(self)
  File "/usr/lib/python3.8/site-packages/gufw/gufw/view/listening.py", line 35, in __init__
    self._show_report()
  File "/usr/lib/python3.8/site-packages/gufw/gufw/view/listening.py", line 48, in _show_report
    self._view_report(report, self.previous_report)
  File "/usr/lib/python3.8/site-packages/gufw/gufw/view/listening.py", line 83, in _view_report
    self.gufw.listening_model.set_value(iter_row, 1, int(line_split[1].strip())) # port
ValueError: invalid literal for int() with base 10: 'WARN:'
```

How to reproduce :

- Archlinux : Install both `mosh` and `ufw-extras` packges
- Other distros : Copy any profile to another file (`# cp /etc/ufw/applications.d/mosh{,2}`)

**Comment by costales** [comment]
Hi,

Do you know how could I replicate that issue in `ufw`?

Best regards.

**Comment by gileri** [comment]
Oh, right ! I updated my first message.

**Comment by costales** [comment]
Hi,

`ufw-extras` doesn't exist in Ubuntu 20.04:

```
costales@T410:~/Desktop/gufw$ apt-cache search ufw | grep extras
costales@T410:~/Desktop/gufw$ dpkg -l | grep ufw | grep extra
costales@T410:~/Desktop/gufw$ 
```

**Comment by costales** [comment]
After checking this, I think the package `ufw-extras` is adding a config file to `ufw`. In my knowledge, the `ufw-extras` is not a distro package and it should not add that file.

**Comment by gileri** [comment]
Hi Costales, thank you for your answer. Please note that I have already addressed both points in the [OP](https://github.com/costales/gufw/issues/9#issue-632784825) :

>How to reproduce :
 >Archlinux : Install both mosh and ufw-extras packges
 >Other distros : Copy any profile to another file (# cp /etc/ufw/applications.d/mosh{,2})

>While this warning should be fixed on my side, it shouldn't crash gufw

You're right that it is an `ufw` configuration error that should be fixed by packagers or users. But I think you'll agree that `WARN` level logs shouldn't crash downstream packages such as `gufw`.

**Comment by noroadsleft000** [comment]
I am also facing same issue. But I am able to UFW command from terminal.

When I try to launch the GUFW from terminal I get below output.

Is something wrong with python path. I am seeing a regular expression * in the path. is that allowed ?
$ ls -l /usr/lib | grep python
drwxr-xr-x  27 root root   24576 May  8 07:20 python2.7
drwxr-xr-x   3 root root    4096 Apr 26  2018 python3
drwxr-xr-x  29 root root   20480 May  8 07:19 python3.6
drwxr-xr-x  31 root root   20480 Jul 25 08:39 python3.8

I have 4 different python versions installed.  
python3.8 does have a site-packages directory inside it. but there is no such package gufw.

ls: cannot access '/usr/lib/python*/site-packages/gufw/gufw.py': No such file or directory
Traceback (most recent call last):
  File "/usr/share/gufw/gufw/gufw.py", line 30, in <module>
    gufw = Gufw(controler.get_frontend())
  File "/usr/share/gufw/gufw/gufw/view/gufw.py", line 80, in __init__
    self._set_initial_values()
  File "/usr/share/gufw/gufw/gufw/view/gufw.py", line 283, in _set_initial_values
    self.listening = ListeningReport(self)
  File "/usr/share/gufw/gufw/gufw/view/listening.py", line 35, in __init__
    self._show_report()
  File "/usr/share/gufw/gufw/gufw/view/listening.py", line 48, in _show_report
    self._view_report(report, self.previous_report)
  File "/usr/share/gufw/gufw/gufw/view/listening.py", line 83, in _view_report
    self.gufw.listening_model.set_value(iter_row, 1, int(line_split[1].strip())) # port
ValueError: invalid literal for int() with base 10: 'WARN:'

**Comment by amitdhiman000** [comment]
I am also facing same issue. But I am able to UFW command from terminal.

When I try to launch the GUFW from terminal I get below output.

Is something wrong with python path. I am seeing a regular expression * in the path. is that allowed ?
$ ls -l /usr/lib | grep python
drwxr-xr-x  27 root root   24576 May  8 07:20 python2.7
drwxr-xr-x   3 root root    4096 Apr 26  2018 python3
drwxr-xr-x  29 root root   20480 May  8 07:19 python3.6
drwxr-xr-x  31 root root   20480 Jul 25 08:39 python3.8

I have 4 different python versions installed.  
python3.8 does have a site-packages directory inside it. but there is no such package gufw.

ls: cannot access '/usr/lib/python*/site-packages/gufw/gufw.py': No such file or directory
Traceback (most recent call last):
  File "/usr/share/gufw/gufw/gufw.py", line 30, in <module>
    gufw = Gufw(controler.get_frontend())
  File "/usr/share/gufw/gufw/gufw/view/gufw.py", line 80, in __init__
    self._set_initial_values()
  File "/usr/share/gufw/gufw/gufw/view/gufw.py", line 283, in _set_initial_values
    self.listening = ListeningReport(self)
  File "/usr/share/gufw/gufw/gufw/view/listening.py", line 35, in __init__
    self._show_report()
  File "/usr/share/gufw/gufw/gufw/view/listening.py", line 48, in _show_report
    self._view_report(report, self.previous_report)
  File "/usr/share/gufw/gufw/gufw/view/listening.py", line 83, in _view_report
    self.gufw.listening_model.set_value(iter_row, 1, int(line_split[1].strip())) # port
ValueError: invalid literal for int() with base 10: 'WARN:'

**Comment by costales** [comment]
Hi,
Could you confirm that the patch is fixing the issue? (sorry the .zip, Github doesn't allow .patch).
Thanks in advance!
[fix_9.zip](https://github.com/costales/gufw/files/5430801/fix_9.zip)

**Comment by amitdhiman000** [comment]
@costales 

facing same issue after applying patch.

user@user-pc:~Downloads$ sudo patch /usr/share/gufw/gufw/gufw/model/ufw_backend.py < fix_9.patch
[sudo] password for user: 
patching file /usr/share/gufw/gufw/gufw/model/ufw_backend.py
user@user-pc:~/Downloads$ sudo gufw
/usr/bin/gufw: line 2: [: =: unary operator expected
ls: cannot access '/usr/lib/python*/site-packages/gufw/gufw.py': No such file or directory
Traceback (most recent call last):
  File "/usr/share/gufw/gufw/gufw.py", line 30, in <module>
    gufw = Gufw(controler.get_frontend())
  File "/usr/share/gufw/gufw/gufw/view/gufw.py", line 80, in __init__
    self._set_initial_values()
  File "/usr/share/gufw/gufw/gufw/view/gufw.py", line 283, in _set_initial_values
    self.listening = ListeningReport(self)
  File "/usr/share/gufw/gufw/gufw/view/listening.py", line 35, in __init__
    self._show_report()
  File "/usr/share/gufw/gufw/gufw/view/listening.py", line 48, in _show_report
    self._view_report(report, self.previous_report)
  File "/usr/share/gufw/gufw/gufw/view/listening.py", line 83, in _view_report
    self.gufw.listening_model.set_value(iter_row, 1, int(line_split[1].strip())) # port
ValueError: invalid literal for int() with base 10: 'ERROR:'

**Comment by gileri** [comment]
> Hi,
> Could you confirm that the patch is fixing the issue? (sorry the .zip, Github doesn't allow .patch).
> Thanks in advance!


Hi @costales, indeed that fixes this issues. May I recommend to also ignore lines starting with [`DEBUG`](https://git.launchpad.net/ufw/tree/src/util.py#n372) ?

PS : Due to [that commit](https://github.com/costales/gufw/commit/efd1fcafb33b8d711e46c9f6202f252d1cf30b79) the arch build doesn't work anymore as it expects to have `gufw.py` residing in `site-packges`

**Comment by costales** [comment]
> facing same issue after applying patch.

@amitdhiman000 Open another issue, this is not related. Thanks.

**Comment by count00zero** [comment]
For me on Ubuntu Groovy that fix_9 solved the Problem!
Thanks a lot!

**Comment by lxs602** [comment]
Hi, 

I get the following error after using the patch on Ubuntu 20.04. 

I get the same message after installing gufw-21.04 from Ubuntu 21.04 (https://packages.ubuntu.com/hirsute/all/gufw/download)

`Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_modifier_mask: assertion 'GDK_IS_KEYMAP (keymap)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(gufw.py:211593): Gtk-CRITICAL **: 20:02:21.762: _gtk_replace_virtual_modifiers: assertion 'GDK_IS_KEYMAP (keymap)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_modifier_mask: assertion 'GDK_IS_KEYMAP (keymap)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(gufw.py:211593): Gtk-CRITICAL **: 20:02:21.762: _gtk_replace_virtual_modifiers: assertion 'GDK_IS_KEYMAP (keymap)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_modifier_mask: assertion 'GDK_IS_KEYMAP (keymap)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(gufw.py:211593): Gtk-CRITICAL **: 20:02:21.762: _gtk_replace_virtual_modifiers: assertion 'GDK_IS_KEYMAP (keymap)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_modifier_mask: assertion 'GDK_IS_KEYMAP (keymap)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(gufw.py:211593): Gtk-CRITICAL **: 20:02:21.762: _gtk_replace_virtual_modifiers: assertion 'GDK_IS_KEYMAP (keymap)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_modifier_mask: assertion 'GDK_IS_KEYMAP (keymap)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(gufw.py:211593): Gtk-CRITICAL **: 20:02:21.762: _gtk_replace_virtual_modifiers: assertion 'GDK_IS_KEYMAP (keymap)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_modifier_mask: assertion 'GDK_IS_KEYMAP (keymap)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(gufw.py:211593): Gtk-CRITICAL **: 20:02:21.762: _gtk_replace_virtual_modifiers: assertion 'GDK_IS_KEYMAP (keymap)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_modifier_mask: assertion 'GDK_IS_KEYMAP (keymap)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(gufw.py:211593): Gtk-CRITICAL **: 20:02:21.762: _gtk_replace_virtual_modifiers: assertion 'GDK_IS_KEYMAP (keymap)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_modifier_mask: assertion 'GDK_IS_KEYMAP (keymap)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(gufw.py:211593): Gtk-CRITICAL **: 20:02:21.762: _gtk_replace_virtual_modifiers: assertion 'GDK_IS_KEYMAP (keymap)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_modifier_mask: assertion 'GDK_IS_KEYMAP (keymap)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(gufw.py:211593): Gtk-CRITICAL **: 20:02:21.762: _gtk_replace_virtual_modifiers: assertion 'GDK_IS_KEYMAP (keymap)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_modifier_mask: assertion 'GDK_IS_KEYMAP (keymap)' failed

(gufw.py:211593): Gdk-CRITICAL **: 20:02:21.762: gdk_keymap_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(gufw.py:211593): Gtk-CRITICAL **: 20:02:21.762: _gtk_replace_virtual_modifiers: assertion 'GDK_IS_KEYMAP (keymap)' failed

(gufw.py:211593): Gtk-CRITICAL **: 20:02:21.763: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(gufw.py:211593): Gtk-CRITICAL **: 20:02:21.763: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(gufw.py:211593): Gtk-CRITICAL **: 20:02:21.763: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed
/usr/bin/gufw-pkexec: line 2: 211593 Segmentation fault      (core dumped) python3 /usr/share/gufw/gufw/gufw.py $1`

Any suggestions?

Thanks

**Comment by pracplayopen** [comment]
also had this issue in linux mint 20.1 (non-upgrade).

fixed w/fix_9.patch tho, thx
